//request.rest

### 1. Contoh : Endpoint API : GET '/'
GET http://localhost:3000/

### 2. Contoh Endpoint API >> GET /oby
GET http://localhost:3000/oby

### 3. POST http://localhost:3000/api/pasien
POST http://localhost:3000/api/pasien
Content-Type: application/json

{
  "nama" : "Tutik",
  "alamat": "Semarang"
}





### 6. READ : Endpoint : GET /api/siswa
GET http://localhost:3000/api/siswa

### 7. READ : Endpoint : GET /api/siswa/:id
GET http://localhost:3000/api/siswa/1

### 7a. Validation READ : Endpoint : GET /api/siswa/:id
//"value" must be a number
GET http://localhost:3000/api/siswa/a

### 8. CREATE : Endpoint : POST /api/siswa
POST http://localhost:3000/api/siswa
Content-Type: application/json

{
"first_name": "Edy",
"last_name": "Kholid",
"email": "edy@gmail.com",
"phone": "84394549570"
}

### 8a. Validation CREATE : Endpoint : POST /api/siswa
//"first_name" is not allowed to be empty
POST http://localhost:3000/api/siswa
Content-Type: application/json

{
"first_name": "",
"last_name": "Kholid",
"email": "edy@gmail.com",
"phone": "84394549570"
}

### 9. DELETE : Endpoint : DELETE /api/siswa/:id
DELETE http://localhost:3000/api/siswa/1

### 9a. Vvalidation DELETE : Endpoint : DELETE /api/siswa/:id
//"value" must be a number
DELETE http://localhost:3000/api/siswa/a

### 10. UPDATE : Endpoint : PUT /api/siswa/:id
PUT http://localhost:3000/api/siswa/1
Content-Type: application/json

{
"first_name": "Silmi",
"last_name": "Ayra-Naifa",
"email": "silmi@gmail.com",
"phone": "48567356790"
}

### 10a. Validation UPDATE : Endpoint : PUT /api/siswa/:id
//"id" must be a number
PUT http://localhost:3000/api/siswa/a
Content-Type: application/json

{
"first_name": "Silmi",
"last_name": "Ayra-Naifa",
"email": "silmi@gmail.com",
"phone": "48567356790"
}

### 10b. Validation UPDATE : Endpoint : PUT /api/siswa/:id
//"first_name" is not allowed to be empty
PUT http://localhost:3000/api/siswa/1
Content-Type: application/json

{
"first_name": "",
"last_name": "Ayra-Naifa",
"email": "silmi@gmail.com",
"phone": "48567356790"
}
